/* ============================================================
   products.js — ДАНІ ТОВАРІВ
   ------------------------------------------------------------
   Щоб додати новий товар — просто скопіюйте будь-який об'єкт
   з масиву PRODUCTS і змініть поля:

   id          — унікальний числовий ідентифікатор
   images      — [основне фото, фото при наведенні] з папки images/
                 (якщо файлу немає, картка покаже сірий фон-заглушку)
   name        — назва товару (українською)
   price       — ціна в гривнях (число)
   oldPrice    — стара ціна (число) або null, якщо знижки немає
   category    — 'tshirts' | 'sweaters' | 'pants' | 'accessories'
   sizes       — доступні розміри: ['S','M','L','XL']
                 (для аксесуарів використовуємо ['ONE'] — один розмір)
   colors      — масив ключів кольорів з об'єкта COLORS (нижче)
   popularity  — 1..100, використовується для сортування «за популярністю»
   createdAt   — дата появи в асортименті 'РРРР-ММ-ДД' (сортування «за новизною»)
   badge       — підпис на картці ('Новинка', '-20%'...) або null
   description — повний опис для вікна швидкого перегляду
   ============================================================ */

// Словник кольорів: ключ -> назва українською + HEX для кружечка
const COLORS = {
  black:  { label: 'Чорний',      hex: '#1a1a1a' },
  white:  { label: 'Білий',       hex: '#f5f5f0' },
  beige:  { label: 'Бежевий',     hex: '#d8c3a5' },
  grey:   { label: 'Сірий',       hex: '#9a9a9a' },
  blue:   { label: 'Синій',       hex: '#2f4a6d' },
  green:  { label: 'Зелений',     hex: '#4a5d54' },
  brown:  { label: 'Коричневий',  hex: '#6b4a35' },
  burgundy:{ label: 'Бордовий',   hex: '#6d1f2c' },
};

// Назви категорій українською (для чипів та карток)
const CATEGORY_LABELS = {
  tshirts: 'Футболки',
  sweaters: 'Светри',
  pants: 'Штани',
  accessories: 'Аксесуари',
};

const PRODUCTS = [
  {
    id: 1,
    images: ['images/p1-1.jpg', 'images/p1-2.jpg'],
    name: 'Футболка oversize «Basic»',
    price: 890,
    oldPrice: 1100,
    category: 'tshirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['black', 'white', 'beige'],
    popularity: 96,
    createdAt: '2026-07-10',
    badge: '-20%',
    description: 'Щільна бавовна 220 г/м², вільний крій, подовжена спинка. Тримає форму після прання, не просвічується. Ідеальна база для щоденних образів.',
  },
  {
    id: 2,
    images: ['images/p2-1.jpg', 'images/p2-2.jpg'],
    name: 'Футболка з кишенею «Pocket»',
    price: 790,
    oldPrice: null,
    category: 'tshirts',
    sizes: ['S', 'M', 'L'],
    colors: ['white', 'grey', 'blue'],
    popularity: 74,
    createdAt: '2026-05-22',
    badge: null,
    description: 'Прямий силует з накладною кишенею на грудях. Бавовна з мінімальним додаванням еластану — комфортна навіть у спеку.',
  },
  {
    id: 3,
    images: ['images/p3-1.jpg', 'images/p3-2.jpg'],
    name: 'Футболка «Long Sleeve»',
    price: 1050,
    oldPrice: null,
    category: 'tshirts',
    sizes: ['M', 'L', 'XL'],
    colors: ['black', 'green', 'burgundy'],
    popularity: 61,
    createdAt: '2026-06-30',
    badge: 'Новинка',
    description: 'Лонгслів із подвійним трикотажем на манжетах. Носиться самостійно або як шар під светр чи сорочку.',
  },
  {
    id: 4,
    images: ['images/p4-1.jpg', 'images/p4-2.jpg'],
    name: 'Светр з мериносу «Wool»',
    price: 3200,
    oldPrice: 3900,
    category: 'sweaters',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['beige', 'grey', 'burgundy'],
    popularity: 98,
    createdAt: '2026-07-18',
    badge: '-18%',
    description: '100% меринос екстрафайн — не колеться, регулює температуру. Класичний круглий виріз, ручна кетлівка горловини.',
  },
  {
    id: 5,
    images: ['images/p5-1.jpg', 'images/p5-2.jpg'],
    name: 'Светр в\'язаний «Cable»',
    price: 2450,
    oldPrice: null,
    category: 'sweaters',
    sizes: ['M', 'L', 'XL'],
    colors: ['white', 'beige', 'blue'],
    popularity: 83,
    createdAt: '2026-06-05',
    badge: null,
    description: 'Об\'ємне косичне в\'язання, вовна з бавовною. Теплий, але дихаючий — комфортно і в приміщенні.',
  },
  {
    id: 6,
    images: ['images/p6-1.jpg', 'images/p6-2.jpg'],
    name: 'Кардиган «Soft»',
    price: 2890,
    oldPrice: null,
    category: 'sweaters',
    sizes: ['S', 'M', 'L'],
    colors: ['grey', 'black', 'brown'],
    popularity: 70,
    createdAt: '2026-07-02',
    badge: 'Новинка',
    description: 'М\'який кардиган на ґудзиках з двома кишенями. Тканина не електризується, підходить для офісу та прогулянок.',
  },
  {
    id: 7,
    images: ['images/p7-1.jpg', 'images/p7-2.jpg'],
    name: 'Штани карго «Utility»',
    price: 1990,
    oldPrice: 2400,
    category: 'pants',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['beige', 'green', 'black'],
    popularity: 91,
    createdAt: '2026-07-20',
    badge: '-17%',
    description: 'Щільна саржа, шість кишень, регульовані манжети знизу. Вільний крій без зайвого об\'єму в стегнах.',
  },
  {
    id: 8,
    images: ['images/p8-1.jpg', 'images/p8-2.jpg'],
    name: 'Штани класичні «Tailored»',
    price: 2350,
    oldPrice: null,
    category: 'pants',
    sizes: ['S', 'M', 'L'],
    colors: ['black', 'grey', 'blue'],
    popularity: 78,
    createdAt: '2026-04-14',
    badge: null,
    description: 'Прямі штани зі стрілками з костюмної тканини. Пояс з внутрішньою гумкою — сидять по фігурі, але не тиснуть.',
  },
  {
    id: 9,
    images: ['images/p9-1.jpg', 'images/p9-2.jpg'],
    name: 'Джогери «Comfort»',
    price: 1450,
    oldPrice: null,
    category: 'pants',
    sizes: ['M', 'L', 'XL'],
    colors: ['grey', 'black', 'brown'],
    popularity: 66,
    createdAt: '2026-05-08',
    badge: null,
    description: 'Тринитка петля без флісу, широкі манжети, куліса на поясі. Найкращий вибір для дому та подорожей.',
  },
  {
    id: 10,
    images: ['images/p10-1.jpg', 'images/p10-2.jpg'],
    name: 'Шкіряний ремінь «Classic»',
    price: 990,
    oldPrice: null,
    category: 'accessories',
    sizes: ['ONE'],
    colors: ['black', 'brown'],
    popularity: 88,
    createdAt: '2026-06-18',
    badge: null,
    description: 'Натуральна шкіра рослинного дублення, латунна пряжка. З часом набуває благородної патини.',
  },
  {
    id: 11,
    images: ['images/p11-1.jpg', 'images/p11-2.jpg'],
    name: 'Шапка-біні «Merino»',
    price: 690,
    oldPrice: 850,
    category: 'accessories',
    sizes: ['ONE'],
    colors: ['black', 'beige', 'burgundy'],
    popularity: 80,
    createdAt: '2026-07-24',
    badge: '-19%',
    description: 'Тонкий меринос подвійного в\'язання. Не колеться, тримає форму, легко вміщується в кишеню.',
  },
  {
    id: 12,
    images: ['images/p12-1.jpg', 'images/p12-2.jpg'],
    name: 'Шкіряна сумка «Daily»',
    price: 3450,
    oldPrice: null,
    category: 'accessories',
    sizes: ['ONE'],
    colors: ['brown', 'black', 'beige'],
    popularity: 93,
    createdAt: '2026-07-26',
    badge: 'Новинка',
    description: 'Компактна сумка через плече з відділенням для ноутбука 13". Ремінь регулюється, підкладка з бавовни.',
  },
  {
    id: 13,
    images: ['images/p13-1.jpg', 'images/p13-2.jpg'],
    name: 'Шарф «Wool Wrap»',
    price: 1190,
    oldPrice: null,
    category: 'accessories',
    sizes: ['ONE'],
    colors: ['grey', 'green', 'burgundy'],
    popularity: 57,
    createdAt: '2026-03-30',
    badge: null,
    description: 'Широкий вовняний шарф із бахромою. Достатньо великий, щоб носити як накидку прохолодним вечором.',
  },
  {
    id: 14,
    images: ['images/p14-1.jpg', 'images/p14-2.jpg'],
    name: 'Худі «Heavy»',
    price: 2150,
    oldPrice: 2600,
    category: 'sweaters',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['black', 'grey', 'green'],
    popularity: 95,
    createdAt: '2026-07-12',
    badge: '-17%',
    description: 'Тринитка 340 г/м², капюшон на подвійному шарі, металеві люверси. Не «сідає» після прання.',
  },
  {
    id: 15,
    images: ['images/p15-1.jpg', 'images/p15-2.jpg'],
    name: 'Футболка «Stripe»',
    price: 950,
    oldPrice: null,
    category: 'tshirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['white', 'blue'],
    popularity: 52,
    createdAt: '2026-02-20',
    badge: null,
    description: 'Класична смужка у морському стилі, довгий рукав. Бавовна ring-spun — щільна та гладенька на дотик.',
  },
  {
    id: 16,
    images: ['images/p16-1.jpg', 'images/p16-2.jpg'],
    name: 'Штани льняні «Summer»',
    price: 1790,
    oldPrice: null,
    category: 'pants',
    sizes: ['S', 'M', 'L'],
    colors: ['white', 'beige', 'blue'],
    popularity: 72,
    createdAt: '2026-06-24',
    badge: null,
    description: '100% льон, вільний крій, широка холоша. Легкі й дихаючі — врятують у найспекотніший день.',
  },
];
